language: java
jdk:
  - oraclejdk7
  - oraclejdk8
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
install:
  - ./gradlew clean build jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)